image: debian/stable
packages:
  - build-essential
  - cmake
  - ninja-build
sources:
  - https://git.sr.ht/~henrytill/lua
tasks:
  - setup: |
      cd lua
      mkdir build-debug
      cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -B build-debug
  - build: |
      cd lua
      cmake --build build-debug
